-- Users seed data
-- Note: Do NOT add passwords you use in real life. Passwords are now saved as clear text. This is very bad from security point of view. We will have a task to encrypt the passwords
INSERT INTO users (email, password) values ('admin@cyf.org', 'admin_password');
INSERT INTO users (email, password) values ('user@cyf.org', 'user_password');

INSERT INTO nationalities (id, nationality) VALUES (1, 'Afghan');
INSERT INTO nationalities (id, nationality) VALUES (2, 'Albanian');
INSERT INTO nationalities (id, nationality) VALUES (3, 'Algerian');
INSERT INTO nationalities (id, nationality) VALUES (4, 'American');
INSERT INTO nationalities (id, nationality) VALUES (5, 'Andorran');
INSERT INTO nationalities (id, nationality) VALUES (6, 'Angolan');
INSERT INTO nationalities (id, nationality) VALUES (7, 'Anguillan');
INSERT INTO nationalities (id, nationality) VALUES (8, 'Argentine');
INSERT INTO nationalities (id, nationality) VALUES (9, 'Armenian');
INSERT INTO nationalities (id, nationality) VALUES (10, 'Australian');
INSERT INTO nationalities (id, nationality) VALUES (11, 'Austrian');
INSERT INTO nationalities (id, nationality) VALUES (12, 'Azerbaijani');
INSERT INTO nationalities (id, nationality) VALUES (13, 'Bahamian');
INSERT INTO nationalities (id, nationality) VALUES (14, 'Bahraini');
INSERT INTO nationalities (id, nationality) VALUES (15, 'Bangladeshi');
INSERT INTO nationalities (id, nationality) VALUES (16, 'Barbadian');
INSERT INTO nationalities (id, nationality) VALUES (17, 'Belarusian');
INSERT INTO nationalities (id, nationality) VALUES (18, 'Belgian');
INSERT INTO nationalities (id, nationality) VALUES (19, 'Belizean');
INSERT INTO nationalities (id, nationality) VALUES (20, 'Beninese');
INSERT INTO nationalities (id, nationality) VALUES (21, 'Bermudian');
INSERT INTO nationalities (id, nationality) VALUES (22, 'Bhutanese');
INSERT INTO nationalities (id, nationality) VALUES (23, 'Bolivian');
INSERT INTO nationalities (id, nationality) VALUES (24, 'Botswanan');
INSERT INTO nationalities (id, nationality) VALUES (25, 'Brazilian');
INSERT INTO nationalities (id, nationality) VALUES (26, 'British');
INSERT INTO nationalities (id, nationality) VALUES (27, 'British Virgin Islander');
INSERT INTO nationalities (id, nationality) VALUES (28, 'Bruneian');
INSERT INTO nationalities (id, nationality) VALUES (29, 'Bulgarian');
INSERT INTO nationalities (id, nationality) VALUES (30, 'Burkinan');
INSERT INTO nationalities (id, nationality) VALUES (31, 'Burmese');
INSERT INTO nationalities (id, nationality) VALUES (32, 'Burundian');
INSERT INTO nationalities (id, nationality) VALUES (33, 'Cambodian');
INSERT INTO nationalities (id, nationality) VALUES (34, 'Cameroonian');
INSERT INTO nationalities (id, nationality) VALUES (35, 'Canadian');
INSERT INTO nationalities (id, nationality) VALUES (36, 'Cape Verdean');
INSERT INTO nationalities (id, nationality) VALUES (37, 'Cayman Islander');
INSERT INTO nationalities (id, nationality) VALUES (38, 'Central African');
INSERT INTO nationalities (id, nationality) VALUES (39, 'Chadian');
INSERT INTO nationalities (id, nationality) VALUES (40, 'Chilean');
INSERT INTO nationalities (id, nationality) VALUES (41, 'Chinese');
INSERT INTO nationalities (id, nationality) VALUES (42, 'Citizen of Antigua and Barbuda');
INSERT INTO nationalities (id, nationality) VALUES (43, 'Citizen of Bosnia and Herzegovina');
INSERT INTO nationalities (id, nationality) VALUES (44, 'Citizen of Guinea-Bissau');
INSERT INTO nationalities (id, nationality) VALUES (45, 'Citizen of Kiribati');
INSERT INTO nationalities (id, nationality) VALUES (46, 'Citizen of Seychelles');
INSERT INTO nationalities (id, nationality) VALUES (47, 'Citizen of the Dominican Republic');
INSERT INTO nationalities (id, nationality) VALUES (48, 'Citizen of Vanuatu');
INSERT INTO nationalities (id, nationality) VALUES (49, 'Colombian');
INSERT INTO nationalities (id, nationality) VALUES (50, 'Comoran');
INSERT INTO nationalities (id, nationality) VALUES (51, 'Congolese (Congo)');
INSERT INTO nationalities (id, nationality) VALUES (52, 'Congolese (DRC)');
INSERT INTO nationalities (id, nationality) VALUES (53, 'Cook Islander');
INSERT INTO nationalities (id, nationality) VALUES (54, 'Costa Rican');
INSERT INTO nationalities (id, nationality) VALUES (55, 'Croatian');
INSERT INTO nationalities (id, nationality) VALUES (56, 'Cuban');
INSERT INTO nationalities (id, nationality) VALUES (57, 'Cymraes');
INSERT INTO nationalities (id, nationality) VALUES (58, 'Cymro');
INSERT INTO nationalities (id, nationality) VALUES (59, 'Cypriot');
INSERT INTO nationalities (id, nationality) VALUES (60, 'Czech');
INSERT INTO nationalities (id, nationality) VALUES (61, 'Danish');
INSERT INTO nationalities (id, nationality) VALUES (62, 'Djiboutian');
INSERT INTO nationalities (id, nationality) VALUES (63, 'Dominican');
INSERT INTO nationalities (id, nationality) VALUES (64, 'Dutch');
INSERT INTO nationalities (id, nationality) VALUES (65, 'East Timorese');
INSERT INTO nationalities (id, nationality) VALUES (66, 'Ecuadorean');
INSERT INTO nationalities (id, nationality) VALUES (67, 'Egyptian');
INSERT INTO nationalities (id, nationality) VALUES (68, 'Emirati');
INSERT INTO nationalities (id, nationality) VALUES (69, 'English');
INSERT INTO nationalities (id, nationality) VALUES (70, 'Equatorial Guinean');
INSERT INTO nationalities (id, nationality) VALUES (71, 'Eritrean');
INSERT INTO nationalities (id, nationality) VALUES (72, 'Estonian');
INSERT INTO nationalities (id, nationality) VALUES (73, 'Ethiopian');
INSERT INTO nationalities (id, nationality) VALUES (74, 'Faroese');
INSERT INTO nationalities (id, nationality) VALUES (75, 'Fijian');
INSERT INTO nationalities (id, nationality) VALUES (76, 'Filipino');
INSERT INTO nationalities (id, nationality) VALUES (77, 'Finnish');
INSERT INTO nationalities (id, nationality) VALUES (78, 'French');
INSERT INTO nationalities (id, nationality) VALUES (79, 'Gabonese');
INSERT INTO nationalities (id, nationality) VALUES (80, 'Gambian');
INSERT INTO nationalities (id, nationality) VALUES (81, 'Georgian');
INSERT INTO nationalities (id, nationality) VALUES (82, 'German');
INSERT INTO nationalities (id, nationality) VALUES (83, 'Ghanaian');
INSERT INTO nationalities (id, nationality) VALUES (84, 'Gibraltarian');
INSERT INTO nationalities (id, nationality) VALUES (85, 'Greek');
INSERT INTO nationalities (id, nationality) VALUES (86, 'Greenlandic');
INSERT INTO nationalities (id, nationality) VALUES (87, 'Grenadian');
INSERT INTO nationalities (id, nationality) VALUES (88, 'Guamanian');
INSERT INTO nationalities (id, nationality) VALUES (89, 'Guatemalan');
INSERT INTO nationalities (id, nationality) VALUES (90, 'Guinean');
INSERT INTO nationalities (id, nationality) VALUES (91, 'Guyanese');
INSERT INTO nationalities (id, nationality) VALUES (92, 'Haitian');
INSERT INTO nationalities (id, nationality) VALUES (93, 'Honduran');
INSERT INTO nationalities (id, nationality) VALUES (94, 'Hong Konger');
INSERT INTO nationalities (id, nationality) VALUES (95, 'Hungarian');
INSERT INTO nationalities (id, nationality) VALUES (96, 'Icelandic');
INSERT INTO nationalities (id, nationality) VALUES (97, 'Indian');
INSERT INTO nationalities (id, nationality) VALUES (98, 'Indonesian');
INSERT INTO nationalities (id, nationality) VALUES (99, 'Iranian');
INSERT INTO nationalities (id, nationality) VALUES (100, 'Iraqi');
INSERT INTO nationalities (id, nationality) VALUES (101, 'Irish');
INSERT INTO nationalities (id, nationality) VALUES (102, 'Israeli');
INSERT INTO nationalities (id, nationality) VALUES (103, 'Italian');
INSERT INTO nationalities (id, nationality) VALUES (104, 'Ivorian');
INSERT INTO nationalities (id, nationality) VALUES (105, 'Jamaican');
INSERT INTO nationalities (id, nationality) VALUES (106, 'Japanese');
INSERT INTO nationalities (id, nationality) VALUES (107, 'Jordanian');
INSERT INTO nationalities (id, nationality) VALUES (108, 'Kazakh');
INSERT INTO nationalities (id, nationality) VALUES (109, 'Kenyan');
INSERT INTO nationalities (id, nationality) VALUES (110, 'Kittitian');
INSERT INTO nationalities (id, nationality) VALUES (111, 'Kosovan');
INSERT INTO nationalities (id, nationality) VALUES (112, 'Kuwaiti');
INSERT INTO nationalities (id, nationality) VALUES (113, 'Kyrgyz');
INSERT INTO nationalities (id, nationality) VALUES (114, 'Lao');
INSERT INTO nationalities (id, nationality) VALUES (115, 'Latvian');
INSERT INTO nationalities (id, nationality) VALUES (116, 'Lebanese');
INSERT INTO nationalities (id, nationality) VALUES (117, 'Liberian');
INSERT INTO nationalities (id, nationality) VALUES (118, 'Libyan');
INSERT INTO nationalities (id, nationality) VALUES (119, 'Liechtenstein citizen');
INSERT INTO nationalities (id, nationality) VALUES (120, 'Lithuanian');
INSERT INTO nationalities (id, nationality) VALUES (121, 'Luxembourger');
INSERT INTO nationalities (id, nationality) VALUES (122, 'Macanese');
INSERT INTO nationalities (id, nationality) VALUES (123, 'Macedonian');
INSERT INTO nationalities (id, nationality) VALUES (124, 'Malagasy');
INSERT INTO nationalities (id, nationality) VALUES (125, 'Malawian');
INSERT INTO nationalities (id, nationality) VALUES (126, 'Malaysian');
INSERT INTO nationalities (id, nationality) VALUES (127, 'Maldivian');
INSERT INTO nationalities (id, nationality) VALUES (128, 'Malian');
INSERT INTO nationalities (id, nationality) VALUES (129, 'Maltese');
INSERT INTO nationalities (id, nationality) VALUES (130, 'Marshallese');
INSERT INTO nationalities (id, nationality) VALUES (131, 'Martiniquais');
INSERT INTO nationalities (id, nationality) VALUES (132, 'Mauritanian');
INSERT INTO nationalities (id, nationality) VALUES (133, 'Mauritian');
INSERT INTO nationalities (id, nationality) VALUES (134, 'Mexican');
INSERT INTO nationalities (id, nationality) VALUES (135, 'Micronesian');
INSERT INTO nationalities (id, nationality) VALUES (136, 'Moldovan');
INSERT INTO nationalities (id, nationality) VALUES (137, 'Monegasque');
INSERT INTO nationalities (id, nationality) VALUES (138, 'Mongolian');
INSERT INTO nationalities (id, nationality) VALUES (139, 'Montenegrin');
INSERT INTO nationalities (id, nationality) VALUES (140, 'Montserratian');
INSERT INTO nationalities (id, nationality) VALUES (141, 'Moroccan');
INSERT INTO nationalities (id, nationality) VALUES (142, 'Mosotho');
INSERT INTO nationalities (id, nationality) VALUES (143, 'Mozambican');
INSERT INTO nationalities (id, nationality) VALUES (144, 'Namibian');
INSERT INTO nationalities (id, nationality) VALUES (145, 'Nauruan');
INSERT INTO nationalities (id, nationality) VALUES (146, 'Nepalese');
INSERT INTO nationalities (id, nationality) VALUES (147, 'New Zealander');
INSERT INTO nationalities (id, nationality) VALUES (148, 'Nicaraguan');
INSERT INTO nationalities (id, nationality) VALUES (149, 'Nigerian');
INSERT INTO nationalities (id, nationality) VALUES (150, 'Nigerien');
INSERT INTO nationalities (id, nationality) VALUES (151, 'Niuean');
INSERT INTO nationalities (id, nationality) VALUES (152, 'North Korean');
INSERT INTO nationalities (id, nationality) VALUES (153, 'Northern Irish');
INSERT INTO nationalities (id, nationality) VALUES (154, 'Norwegian');
INSERT INTO nationalities (id, nationality) VALUES (155, 'Omani');
INSERT INTO nationalities (id, nationality) VALUES (156, 'Pakistani');
INSERT INTO nationalities (id, nationality) VALUES (157, 'Palauan');
INSERT INTO nationalities (id, nationality) VALUES (158, 'Palestinian');
INSERT INTO nationalities (id, nationality) VALUES (159, 'Panamanian');
INSERT INTO nationalities (id, nationality) VALUES (160, 'Papua New Guinean');
INSERT INTO nationalities (id, nationality) VALUES (161, 'Paraguayan');
INSERT INTO nationalities (id, nationality) VALUES (162, 'Peruvian');
INSERT INTO nationalities (id, nationality) VALUES (163, 'Pitcairn Islander');
INSERT INTO nationalities (id, nationality) VALUES (164, 'Polish');
INSERT INTO nationalities (id, nationality) VALUES (165, 'Portuguese');
INSERT INTO nationalities (id, nationality) VALUES (166, 'Prydeinig');
INSERT INTO nationalities (id, nationality) VALUES (167, 'Puerto Rican');
INSERT INTO nationalities (id, nationality) VALUES (168, 'Qatari');
INSERT INTO nationalities (id, nationality) VALUES (169, 'Romanian');
INSERT INTO nationalities (id, nationality) VALUES (170, 'Russian');
INSERT INTO nationalities (id, nationality) VALUES (171, 'Rwandan');
INSERT INTO nationalities (id, nationality) VALUES (172, 'Salvadorean');
INSERT INTO nationalities (id, nationality) VALUES (173, 'Sammarinese');
INSERT INTO nationalities (id, nationality) VALUES (174, 'Samoan');
INSERT INTO nationalities (id, nationality) VALUES (175, 'Sao Tomean');
INSERT INTO nationalities (id, nationality) VALUES (176, 'Saudi Arabian');
INSERT INTO nationalities (id, nationality) VALUES (177, 'Scottish');
INSERT INTO nationalities (id, nationality) VALUES (178, 'Senegalese');
INSERT INTO nationalities (id, nationality) VALUES (179, 'Serbian');
INSERT INTO nationalities (id, nationality) VALUES (180, 'Sierra Leonean');
INSERT INTO nationalities (id, nationality) VALUES (181, 'Singaporean');
INSERT INTO nationalities (id, nationality) VALUES (182, 'Slovak');
INSERT INTO nationalities (id, nationality) VALUES (183, 'Slovenian');
INSERT INTO nationalities (id, nationality) VALUES (184, 'Solomon Islander');
INSERT INTO nationalities (id, nationality) VALUES (185, 'Somali');
INSERT INTO nationalities (id, nationality) VALUES (186, 'South African');
INSERT INTO nationalities (id, nationality) VALUES (187, 'South Korean');
INSERT INTO nationalities (id, nationality) VALUES (188, 'South Sudanese');
INSERT INTO nationalities (id, nationality) VALUES (189, 'Spanish');
INSERT INTO nationalities (id, nationality) VALUES (190, 'Sri Lankan');
INSERT INTO nationalities (id, nationality) VALUES (191, 'St Helenian');
INSERT INTO nationalities (id, nationality) VALUES (192, 'St Lucian');
INSERT INTO nationalities (id, nationality) VALUES (193, 'Stateless');
INSERT INTO nationalities (id, nationality) VALUES (194, 'Sudanese');
INSERT INTO nationalities (id, nationality) VALUES (195, 'Surinamese');
INSERT INTO nationalities (id, nationality) VALUES (196, 'Swazi');
INSERT INTO nationalities (id, nationality) VALUES (197, 'Swedish');
INSERT INTO nationalities (id, nationality) VALUES (198, 'Swiss');
INSERT INTO nationalities (id, nationality) VALUES (199, 'Syrian');
INSERT INTO nationalities (id, nationality) VALUES (200, 'Taiwanese');
INSERT INTO nationalities (id, nationality) VALUES (201, 'Tajik');
INSERT INTO nationalities (id, nationality) VALUES (202, 'Tanzanian');
INSERT INTO nationalities (id, nationality) VALUES (203, 'Thai');
INSERT INTO nationalities (id, nationality) VALUES (204, 'Togolese');
INSERT INTO nationalities (id, nationality) VALUES (205, 'Tongan');
INSERT INTO nationalities (id, nationality) VALUES (206, 'Trinidadian');
INSERT INTO nationalities (id, nationality) VALUES (207, 'Tristanian');
INSERT INTO nationalities (id, nationality) VALUES (208, 'Tunisian');
INSERT INTO nationalities (id, nationality) VALUES (209, 'Turkish');
INSERT INTO nationalities (id, nationality) VALUES (210, 'Turkmen');
INSERT INTO nationalities (id, nationality) VALUES (211, 'Turks and Caicos Islander');
INSERT INTO nationalities (id, nationality) VALUES (212, 'Tuvaluan');
INSERT INTO nationalities (id, nationality) VALUES (213, 'Ugandan');
INSERT INTO nationalities (id, nationality) VALUES (214, 'Ukrainian');
INSERT INTO nationalities (id, nationality) VALUES (215, 'Uruguayan');
INSERT INTO nationalities (id, nationality) VALUES (216, 'Uzbek');
INSERT INTO nationalities (id, nationality) VALUES (217, 'Vatican citizen');
INSERT INTO nationalities (id, nationality) VALUES (218, 'Venezuelan');
INSERT INTO nationalities (id, nationality) VALUES (219, 'Vietnamese');
INSERT INTO nationalities (id, nationality) VALUES (220, 'Vincentian');
INSERT INTO nationalities (id, nationality) VALUES (221, 'Wallisian');
INSERT INTO nationalities (id, nationality) VALUES (222, 'Welsh');
INSERT INTO nationalities (id, nationality) VALUES (223, 'Yemeni');
INSERT INTO nationalities (id, nationality) VALUES (224, 'Zambian');
INSERT INTO nationalities (id, nationality) VALUES (225, 'Zimbabwean');



INSERT INTO profiles (first_name, last_name, gender, nationality_id, email, type) values ('Fatma', 'Oymak', 'female', 209, 'sun@cyf.org', 'service_user');
INSERT INTO profiles (first_name, last_name, gender, email, type) values ('Su', 'Oymak', 'female', 'water@cyf.org', 'service_user');
INSERT INTO profiles (first_name, last_name, gender, email, address, type) values ('Gun', 'Ozguven', 'male', 'bedizma@cyf.org', '29, White hart lane, N8 1UG', 'service_user');
INSERT INTO profiles (first_name, last_name, gender, date_of_birth, email, address, type) values ('Arda', 'Acar', 'male', '2008-07-30', 's@cyf.org', '1 Glasgow street, Edinburgh', 'service_user');
INSERT INTO profiles (first_name, last_name, gender, date_of_birth, email, address, type) values ('Natalia', 'Andrei', 'female', '1950-07-05', 'nat_and@cyf.org', '176 Battal Gazi sok., Dalaman', 'service_user');
INSERT INTO profiles (first_name, last_name, gender, nationality_id, date_of_birth, email, address, type) values ('Rares', 'Smith', 'male', 200, '1989-10-15', 'rares_smith@cyf.org', '6 Seyfettin ince cad., Dalaman', 'service_user');
INSERT INTO profiles (first_name, last_name, gender, nationality_id, date_of_birth, email, address, phone_number, occupation, type) values ('Mimi', 'Mouse', 'female', 100, '1967-01-30', 'happy_mood@cyf.org', '176 Battal Gazi sok., Dalaman', '+44 1345 56788', 'teacher', 'service_user');

